login.php
Giuseppe5000/TecWeb pull request #42
Opened 2024-12-22 23:38 UTC by Perruzz

close #32 

scusate sono tornato a casa adesso da parenti e non ho nemmeno finito di guardare, ci sono sicuramente errori e robe da sistemare, ditemi pure però se ho fatto qualcosa che non va che sistemo appena possibile. buonanotte :-3

2024-12-23 18:39 UTC, Perruzz commented
- [ ] finire di sistemare condizioni
- [ ] ricontrollare funzioni dbConnection.php

2024-12-24 08:11 UTC, Giuseppe5000 commented
Il login non funziona, ho dato un'occhiata veloce e ho notato che la funzione password_verify è usata in modo errato, visto che il secondo argomento deve essere un hash (infatti bisogna cambiare le password degli utenti con i relativi hash).
Poi il session_start() deve essere chiamato all'inizio del file e non solo quando setto $_SESSION, tutti gli utenti possono avere una sessione, per capire se sono autenticati si va a guardare $_SESSION['username'].
Potrebbero esserci altri errori comunque, quindi ti direi di riguardare un po' tutto il codice e consultare la documentazione quando usi certe funzioni di php.
Infine eviterei di usare il die per gli errori ma piuttosto fare un echo con exit(1).

2024-12-24 08:14 UTC, Giuseppe5000 commented
Comunque eviterei di collegare più issue alla stessa PR, visto che rallenta la correzione. Per questa volta lascia così ma più in avanti meglio aprire due PR separate.
Inoltre nei messaggi di commit sarebbe più utile avere una descrizione più precisa quando possibile (non troppo lunga obv).

2024-12-24 10:29 UTC, Perruzz commented
> Comunque eviterei di collegare più issue alla stessa PR, visto che rallenta la correzione. Per questa volta lascia così ma più in avanti meglio aprire due PR separate. Inoltre nei messaggi di commit sarebbe più utile avere una descrizione più precisa quando possibile (non troppo lunga obv).

ok perfetto

2024-12-24 11:16 UTC, Perruzz commented on src/php/dbConnection.php
> +                continue; //il regex dell'hash l'ho trovato su stackoverflow, da verificare se funziona, l'obiettivo sarebbe quello di saltare le password già convertite
come scritto nel commento

2024-12-28 14:17 UTC, Giuseppe5000 commented
È pronta per la review? Perchè in un commento vedo una checkbox non spuntata.

2024-12-28 14:19 UTC, Perruzz commented
> È pronta per la review? Perchè in un commento vedo una checkbox non spuntata.
> Nel caso in cui non fosse ancora pronta metti la PR in draft in modo da non fare review su cose non ancora completate.

si

2024-12-28 14:34 UTC, Giuseppe5000 commented on src/php/accedi.php
> +		$connessione->closeConnection();
La connessione si dovrebbe chiudere subito dopo la query di riga 38

2024-12-28 14:39 UTC, Giuseppe5000 requested changes
Tutto bene, solo una piccola cosa da sistemare

2024-12-28 14:40 UTC, Perruzz commented
5 minuti e sistemo

2024-12-29 09:43 UTC, Giuseppe5000 approved these changes

2024-12-29 09:43 UTC, merged